### PR TITLE
Add sraa listing endpoint

### PR DESCRIPTION
**Pull request by thijskh**

### CODE REVIEW

**Comment by thijskh** [comment]
Unfortunalety no significant fixtures present for the tests so cannot really test that it works in the unit test other than that it correctly outputs the empty list and authorizations.

**Comment by MKodde** [comment]
Lookin' good @thijskh,

Two small nitpicks after a code review1:
- The year of the test case is set to 2014, can be set to 2022
- I usually also include the new endpoint to the Postman collection. (we use version 2 of collections when exporting). If you like, I can update this after my functional test of this feature.

I'm planning to run a functional test next. Please wait with hitting the merge button for a sec please ;)

**Comment by thijskh** [comment]
If you can fix the postman, that would be great. I don't think the copyright year is meaningful.

**Comment by MKodde** [comment]
Functional review: 
- No findings, SRAA's where listed as expected

And as promised, I updated the Postman collection.

:shipit:

**Review by MKodde — APPROVED** [review]

**Pull request merged**
